// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "PKief"
export const name = "material-icon-theme"
export const version = "5.31.0"
export const displayName = "Material Icon Theme"
export const description = "Material Design Icons for Visual Studio Code"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "material-icon-theme.activateIcons"
  | "material-icon-theme.toggleIconPacks"
  | "material-icon-theme.changeFolderTheme"
  | "material-icon-theme.changeFolderColor"
  | "material-icon-theme.changeRootFolderColor"
  | "material-icon-theme.changeFileColor"
  | "material-icon-theme.restoreDefaultConfig"
  | "material-icon-theme.toggleExplorerArrows"
  | "material-icon-theme.changeOpacity"
  | "material-icon-theme.toggleGrayscale"
  | "material-icon-theme.changeSaturation"

/**
 * Commands map registered by `PKief.material-icon-theme`
 */
export const commands = {
  /**
   * Material Icons: Activate Icon Theme
   * @value `material-icon-theme.activateIcons`
   */
  activateIcons: "material-icon-theme.activateIcons",
  /**
   * Material Icons: Configure Icon Packs
   * @value `material-icon-theme.toggleIconPacks`
   */
  toggleIconPacks: "material-icon-theme.toggleIconPacks",
  /**
   * Material Icons: Change Folder Theme
   * @value `material-icon-theme.changeFolderTheme`
   */
  changeFolderTheme: "material-icon-theme.changeFolderTheme",
  /**
   * Material Icons: Change Folder Color
   * @value `material-icon-theme.changeFolderColor`
   */
  changeFolderColor: "material-icon-theme.changeFolderColor",
  /**
   * Material Icons: Change Root Folder Color
   * @value `material-icon-theme.changeRootFolderColor`
   */
  changeRootFolderColor: "material-icon-theme.changeRootFolderColor",
  /**
   * Material Icons: Change File Color
   * @value `material-icon-theme.changeFileColor`
   */
  changeFileColor: "material-icon-theme.changeFileColor",
  /**
   * Material Icons: Restore Default Configuration
   * @value `material-icon-theme.restoreDefaultConfig`
   */
  restoreDefaultConfig: "material-icon-theme.restoreDefaultConfig",
  /**
   * Material Icons: Toggle Explorer Arrows
   * @value `material-icon-theme.toggleExplorerArrows`
   */
  toggleExplorerArrows: "material-icon-theme.toggleExplorerArrows",
  /**
   * Material Icons: Change Opacity
   * @value `material-icon-theme.changeOpacity`
   */
  changeOpacity: "material-icon-theme.changeOpacity",
  /**
   * Material Icons: Toggle Grayscale
   * @value `material-icon-theme.toggleGrayscale`
   */
  toggleGrayscale: "material-icon-theme.toggleGrayscale",
  /**
   * Material Icons: Change Saturation
   * @value `material-icon-theme.changeSaturation`
   */
  changeSaturation: "material-icon-theme.changeSaturation",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "material-icon-theme.activeIconPack"
  | "material-icon-theme.files.associations"
  | "material-icon-theme.folders.associations"
  | "material-icon-theme.rootFolders.associations"
  | "material-icon-theme.languages.associations"
  | "material-icon-theme.files.customClones"
  | "material-icon-theme.languages.customClones"
  | "material-icon-theme.folders.customClones"
  | "material-icon-theme.folders.theme"
  | "material-icon-theme.folders.color"
  | "material-icon-theme.rootFolders.color"
  | "material-icon-theme.files.color"
  | "material-icon-theme.opacity"
  | "material-icon-theme.hidesExplorerArrows"
  | "material-icon-theme.saturation"
  | "material-icon-theme.enableLogging"
  | "material-icon-theme.logLevel"

export interface ConfigKeyTypeMap {
  "material-icon-theme.activeIconPack": ("angular" | "angular_ngrx" | "react" | "react_redux" | "roblox" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none"),
  "material-icon-theme.files.associations": Record<string, unknown>,
  "material-icon-theme.folders.associations": Record<string, unknown>,
  "material-icon-theme.rootFolders.associations": Record<string, unknown>,
  "material-icon-theme.languages.associations": Record<string, unknown>,
  "material-icon-theme.files.customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'fileNames'?: string[]; 'fileExtensions'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  "material-icon-theme.languages.customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'ids'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  "material-icon-theme.folders.customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'folderNames'?: string[]; 'rootFolderNames'?: string[] }[],
  "material-icon-theme.folders.theme": ("specific" | "classic" | "none"),
  "material-icon-theme.folders.color": string,
  "material-icon-theme.rootFolders.color": string,
  "material-icon-theme.files.color": string,
  "material-icon-theme.opacity": number,
  "material-icon-theme.hidesExplorerArrows": boolean,
  "material-icon-theme.saturation": number,
  "material-icon-theme.enableLogging": boolean,
  "material-icon-theme.logLevel": ("info" | "error" | "debug"),
}

export interface ConfigShorthandMap {
  activeIconPack: "material-icon-theme.activeIconPack",
  filesAssociations: "material-icon-theme.files.associations",
  foldersAssociations: "material-icon-theme.folders.associations",
  rootFoldersAssociations: "material-icon-theme.rootFolders.associations",
  languagesAssociations: "material-icon-theme.languages.associations",
  filesCustomClones: "material-icon-theme.files.customClones",
  languagesCustomClones: "material-icon-theme.languages.customClones",
  foldersCustomClones: "material-icon-theme.folders.customClones",
  foldersTheme: "material-icon-theme.folders.theme",
  foldersColor: "material-icon-theme.folders.color",
  rootFoldersColor: "material-icon-theme.rootFolders.color",
  filesColor: "material-icon-theme.files.color",
  opacity: "material-icon-theme.opacity",
  hidesExplorerArrows: "material-icon-theme.hidesExplorerArrows",
  saturation: "material-icon-theme.saturation",
  enableLogging: "material-icon-theme.enableLogging",
  logLevel: "material-icon-theme.logLevel",
}

export interface ConfigShorthandTypeMap {
  activeIconPack: ("angular" | "angular_ngrx" | "react" | "react_redux" | "roblox" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none"),
  filesAssociations: Record<string, unknown>,
  foldersAssociations: Record<string, unknown>,
  rootFoldersAssociations: Record<string, unknown>,
  languagesAssociations: Record<string, unknown>,
  filesCustomClones: { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'fileNames'?: string[]; 'fileExtensions'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  languagesCustomClones: { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'ids'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  foldersCustomClones: { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'folderNames'?: string[]; 'rootFolderNames'?: string[] }[],
  foldersTheme: ("specific" | "classic" | "none"),
  foldersColor: string,
  rootFoldersColor: string,
  filesColor: string,
  opacity: number,
  hidesExplorerArrows: boolean,
  saturation: number,
  enableLogging: boolean,
  logLevel: ("info" | "error" | "debug"),
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `PKief.material-icon-theme`
 */
export const configs = {
  /**
   * Select an icon pack that enables specific icons.
   * @key `material-icon-theme.activeIconPack`
   * @default `"angular"`
   * @type `string`
   */
  activeIconPack: {
    key: "material-icon-theme.activeIconPack",
    default: "angular",
  } as ConfigItem<"material-icon-theme.activeIconPack">,
  /**
   * Set custom file icon associations.
   * @key `material-icon-theme.files.associations`
   * @default `{}`
   * @type `object`
   */
  filesAssociations: {
    key: "material-icon-theme.files.associations",
    default: {},
  } as ConfigItem<"material-icon-theme.files.associations">,
  /**
   * Set custom folder icon associations.
   * @key `material-icon-theme.folders.associations`
   * @default `{}`
   * @type `object`
   */
  foldersAssociations: {
    key: "material-icon-theme.folders.associations",
    default: {},
  } as ConfigItem<"material-icon-theme.folders.associations">,
  /**
   * Set custom root folder icon associations.
   * @key `material-icon-theme.rootFolders.associations`
   * @default `{}`
   * @type `object`
   */
  rootFoldersAssociations: {
    key: "material-icon-theme.rootFolders.associations",
    default: {},
  } as ConfigItem<"material-icon-theme.rootFolders.associations">,
  /**
   * Set custom language icon associations.
   * @key `material-icon-theme.languages.associations`
   * @default `{}`
   * @type `object`
   */
  languagesAssociations: {
    key: "material-icon-theme.languages.associations",
    default: {},
  } as ConfigItem<"material-icon-theme.languages.associations">,
  /**
   * Clone any existing icon and create a new one with custom colors and associations
   * @key `material-icon-theme.files.customClones`
   * @default `[]`
   * @type `array`
   */
  filesCustomClones: {
    key: "material-icon-theme.files.customClones",
    default: [],
  } as ConfigItem<"material-icon-theme.files.customClones">,
  /**
   * Clone any existing icon and create a new one with custom colors and associations
   * @key `material-icon-theme.languages.customClones`
   * @default `[]`
   * @type `array`
   */
  languagesCustomClones: {
    key: "material-icon-theme.languages.customClones",
    default: [],
  } as ConfigItem<"material-icon-theme.languages.customClones">,
  /**
   * Clone any existing icon and create a new one with custom colors and associations
   * @key `material-icon-theme.folders.customClones`
   * @default `[]`
   * @type `array`
   */
  foldersCustomClones: {
    key: "material-icon-theme.folders.customClones",
    default: [],
  } as ConfigItem<"material-icon-theme.folders.customClones">,
  /**
   * Set the type for the folder icons.
   * @key `material-icon-theme.folders.theme`
   * @default `"specific"`
   * @type `string`
   */
  foldersTheme: {
    key: "material-icon-theme.folders.theme",
    default: "specific",
  } as ConfigItem<"material-icon-theme.folders.theme">,
  /**
   * Change the color of the folder icons.
   * @key `material-icon-theme.folders.color`
   * @default `"#90a4ae"`
   * @type `string`
   */
  foldersColor: {
    key: "material-icon-theme.folders.color",
    default: "#90a4ae",
  } as ConfigItem<"material-icon-theme.folders.color">,
  /**
   * Change the color of the root folder icons.
   * @key `material-icon-theme.rootFolders.color`
   * @default `"#90a4ae"`
   * @type `string`
   */
  rootFoldersColor: {
    key: "material-icon-theme.rootFolders.color",
    default: "#90a4ae",
  } as ConfigItem<"material-icon-theme.rootFolders.color">,
  /**
   * Change the color of the file icons.
   * @key `material-icon-theme.files.color`
   * @default `"#90a4ae"`
   * @type `string`
   */
  filesColor: {
    key: "material-icon-theme.files.color",
    default: "#90a4ae",
  } as ConfigItem<"material-icon-theme.files.color">,
  /**
   * Change the opacity of the icons.
   * @key `material-icon-theme.opacity`
   * @default `1`
   * @type `number`
   */
  opacity: {
    key: "material-icon-theme.opacity",
    default: 1,
  } as ConfigItem<"material-icon-theme.opacity">,
  /**
   * Hide explorer arrows before folder.
   * @key `material-icon-theme.hidesExplorerArrows`
   * @default `false`
   * @type `boolean`
   */
  hidesExplorerArrows: {
    key: "material-icon-theme.hidesExplorerArrows",
    default: false,
  } as ConfigItem<"material-icon-theme.hidesExplorerArrows">,
  /**
   * Change the saturation of the icons.
   * @key `material-icon-theme.saturation`
   * @default `1`
   * @type `number`
   */
  saturation: {
    key: "material-icon-theme.saturation",
    default: 1,
  } as ConfigItem<"material-icon-theme.saturation">,
  /**
   * Enable logging to the output channel.
   * @key `material-icon-theme.enableLogging`
   * @default `false`
   * @type `boolean`
   */
  enableLogging: {
    key: "material-icon-theme.enableLogging",
    default: false,
  } as ConfigItem<"material-icon-theme.enableLogging">,
  /**
   * Set the log level for output messages.
   * @key `material-icon-theme.logLevel`
   * @default `"info"`
   * @type `string`
   */
  logLevel: {
    key: "material-icon-theme.logLevel",
    default: "info",
  } as ConfigItem<"material-icon-theme.logLevel">,
}

export interface ScopedConfigKeyTypeMap {
  "activeIconPack": ("angular" | "angular_ngrx" | "react" | "react_redux" | "roblox" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none"),
  "files.associations": Record<string, unknown>,
  "folders.associations": Record<string, unknown>,
  "rootFolders.associations": Record<string, unknown>,
  "languages.associations": Record<string, unknown>,
  "files.customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'fileNames'?: string[]; 'fileExtensions'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  "languages.customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'ids'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  "folders.customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'folderNames'?: string[]; 'rootFolderNames'?: string[] }[],
  "folders.theme": ("specific" | "classic" | "none"),
  "folders.color": string,
  "rootFolders.color": string,
  "files.color": string,
  "opacity": number,
  "hidesExplorerArrows": boolean,
  "saturation": number,
  "enableLogging": boolean,
  "logLevel": ("info" | "error" | "debug"),
}

export const scopedConfigs = {
  scope: "material-icon-theme",
  defaults: {
    "activeIconPack": "angular",
    "files.associations": {},
    "folders.associations": {},
    "rootFolders.associations": {},
    "languages.associations": {},
    "files.customClones": [],
    "languages.customClones": [],
    "folders.customClones": [],
    "folders.theme": "specific",
    "folders.color": "#90a4ae",
    "rootFolders.color": "#90a4ae",
    "files.color": "#90a4ae",
    "opacity": 1,
    "hidesExplorerArrows": false,
    "saturation": 1,
    "enableLogging": false,
    "logLevel": "info",
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "material-icon-theme": {
    "activeIconPack": ("angular" | "angular_ngrx" | "react" | "react_redux" | "roblox" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none"),
    "files": {
      "associations": Record<string, unknown>,
      "customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'fileNames'?: string[]; 'fileExtensions'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
      "color": string,
    },
    "folders": {
      "associations": Record<string, unknown>,
      "customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'folderNames'?: string[]; 'rootFolderNames'?: string[] }[],
      "theme": ("specific" | "classic" | "none"),
      "color": string,
    },
    "rootFolders": {
      "associations": Record<string, unknown>,
      "color": string,
    },
    "languages": {
      "associations": Record<string, unknown>,
      "customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'ids'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
    },
    "opacity": number,
    "hidesExplorerArrows": boolean,
    "saturation": number,
    "enableLogging": boolean,
    "logLevel": ("info" | "error" | "debug"),
  },
}

export interface NestedScopedConfigs {
  "activeIconPack": ("angular" | "angular_ngrx" | "react" | "react_redux" | "roblox" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none"),
  "files": {
    "associations": Record<string, unknown>,
    "customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'fileNames'?: string[]; 'fileExtensions'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
    "color": string,
  },
  "folders": {
    "associations": Record<string, unknown>,
    "customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'folderNames'?: string[]; 'rootFolderNames'?: string[] }[],
    "theme": ("specific" | "classic" | "none"),
    "color": string,
  },
  "rootFolders": {
    "associations": Record<string, unknown>,
    "color": string,
  },
  "languages": {
    "associations": Record<string, unknown>,
    "customClones": { 'name'?: string; 'base'?: string; 'color'?: string; 'lightColor'?: string; 'ids'?: string[]; 'activeForPacks'?: ("angular" | "angular_ngrx" | "react" | "react_redux" | "qwik" | "vue" | "vue_vuex" | "nest" | "bashly" | "none")[] }[],
  },
  "opacity": number,
  "hidesExplorerArrows": boolean,
  "saturation": number,
  "enableLogging": boolean,
  "logLevel": ("info" | "error" | "debug"),
}

