// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "vscjava"
export const name = "vscode-java-dependency"
export const version = "0.27.0"
export const displayName = "Project Manager for Java"
export const description = "%description%"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "java.project.create"
  | "_java.project.create.from.menus.file"
  | "_java.project.create.from.fileexplorer.menu"
  | "_java.project.create.from.fileexplorer.welcome"
  | "_java.project.create.from.javaprojectexplorer.welcome"
  | "_java.project.create.from.javaprojectexplorer"
  | "java.project.addLibraries"
  | "java.project.addLibraryFolders"
  | "java.project.removeLibrary"
  | "java.project.refreshLibraries"
  | "java.project.build.workspace"
  | "java.project.clean.workspace"
  | "java.project.update"
  | "java.project.reloadProjectFromActiveFile"
  | "java.project.rebuild"
  | "java.view.package.revealInProjectExplorer"
  | "java.view.package.refresh"
  | "java.view.package.changeToHierarchicalPackageView"
  | "java.view.package.changeToFlatPackageView"
  | "java.view.package.linkWithFolderExplorer"
  | "java.view.package.unlinkWithFolderExplorer"
  | "java.project.explorer.showNonJavaResources"
  | "java.project.explorer.hideNonJavaResources"
  | "java.view.package.revealFileInOS"
  | "java.view.package.exportJar"
  | "java.view.package.copyFilePath"
  | "java.view.package.copyRelativeFilePath"
  | "java.view.package.new"
  | "java.view.menus.file.newJavaClass"
  | "java.view.package.newJavaClass"
  | "java.view.package.newJavaInterface"
  | "java.view.package.newJavaEnum"
  | "java.view.package.newJavaRecord"
  | "java.view.package.newJavaAnnotation"
  | "java.view.package.newJavaAbstractClass"
  | "java.view.package.newPackage"
  | "java.view.fileExplorer.newPackage"
  | "java.view.package.newFile"
  | "java.view.package.newFolder"
  | "java.view.package.moveFileToTrash"
  | "java.view.package.deleteFilePermanently"
  | "java.view.package.renameFile"
  | "_java.view.modernizeJavaProject"
  | "_java.upgradeWithCopilot"

/**
 * Commands map registered by `vscjava.vscode-java-dependency`
 */
export const commands = {
  /**
   * %contributes.commands.java.project.create%
   * @value `java.project.create`
   */
  javaProjectCreate: "java.project.create",
  /**
   * %contributes.commands.java.project.new%
   * @value `_java.project.create.from.menus.file`
   */
  javaProjectCreateFromMenusFile: "_java.project.create.from.menus.file",
  /**
   * %contributes.commands.java.project.new%
   * @value `_java.project.create.from.fileexplorer.menu`
   */
  javaProjectCreateFromFileexplorerMenu: "_java.project.create.from.fileexplorer.menu",
  /**
   * %contributes.commands.java.project.create%
   * @value `_java.project.create.from.fileexplorer.welcome`
   */
  javaProjectCreateFromFileexplorerWelcome: "_java.project.create.from.fileexplorer.welcome",
  /**
   * %contributes.commands.java.project.create%
   * @value `_java.project.create.from.javaprojectexplorer.welcome`
   */
  javaProjectCreateFromJavaprojectexplorerWelcome: "_java.project.create.from.javaprojectexplorer.welcome",
  /**
   * %contributes.commands.java.project.create%
   * @value `_java.project.create.from.javaprojectexplorer`
   */
  javaProjectCreateFromJavaprojectexplorer: "_java.project.create.from.javaprojectexplorer",
  /**
   * %contributes.commands.java.project.addLibraries%
   * @value `java.project.addLibraries`
   */
  javaProjectAddLibraries: "java.project.addLibraries",
  /**
   * %contributes.commands.java.project.addLibraryFolders%
   * @value `java.project.addLibraryFolders`
   */
  javaProjectAddLibraryFolders: "java.project.addLibraryFolders",
  /**
   * %contributes.commands.java.project.removeLibrary%
   * @value `java.project.removeLibrary`
   */
  javaProjectRemoveLibrary: "java.project.removeLibrary",
  /**
   * %contributes.commands.java.view.package.refresh%
   * @value `java.project.refreshLibraries`
   */
  javaProjectRefreshLibraries: "java.project.refreshLibraries",
  /**
   * %contributes.commands.java.project.build.workspace%
   * @value `java.project.build.workspace`
   */
  javaProjectBuildWorkspace: "java.project.build.workspace",
  /**
   * %contributes.commands.java.project.clean.workspace%
   * @value `java.project.clean.workspace`
   */
  javaProjectCleanWorkspace: "java.project.clean.workspace",
  /**
   * %contributes.commands.java.project.update%
   * @value `java.project.update`
   */
  javaProjectUpdate: "java.project.update",
  /**
   * %contributes.commands.java.project.reloadProjectFromActiveFile%
   * @value `java.project.reloadProjectFromActiveFile`
   */
  javaProjectReloadProjectFromActiveFile: "java.project.reloadProjectFromActiveFile",
  /**
   * %contributes.commands.java.project.rebuild%
   * @value `java.project.rebuild`
   */
  javaProjectRebuild: "java.project.rebuild",
  /**
   * %contributes.commands.java.view.package.revealInProjectExplorer%
   * @value `java.view.package.revealInProjectExplorer`
   */
  javaViewPackageRevealInProjectExplorer: "java.view.package.revealInProjectExplorer",
  /**
   * %contributes.commands.java.view.package.refresh%
   * @value `java.view.package.refresh`
   */
  javaViewPackageRefresh: "java.view.package.refresh",
  /**
   * %contributes.commands.java.view.package.changeToHierarchicalPackageView%
   * @value `java.view.package.changeToHierarchicalPackageView`
   */
  javaViewPackageChangeToHierarchicalPackageView: "java.view.package.changeToHierarchicalPackageView",
  /**
   * %contributes.commands.java.view.package.changeToFlatPackageView%
   * @value `java.view.package.changeToFlatPackageView`
   */
  javaViewPackageChangeToFlatPackageView: "java.view.package.changeToFlatPackageView",
  /**
   * %contributes.commands.java.view.package.linkWithFolderExplorer%
   * @value `java.view.package.linkWithFolderExplorer`
   */
  javaViewPackageLinkWithFolderExplorer: "java.view.package.linkWithFolderExplorer",
  /**
   * %contributes.commands.java.view.package.unlinkWithFolderExplorer%
   * @value `java.view.package.unlinkWithFolderExplorer`
   */
  javaViewPackageUnlinkWithFolderExplorer: "java.view.package.unlinkWithFolderExplorer",
  /**
   * %contributes.commands.java.project.explorer.showNonJavaResources%
   * @value `java.project.explorer.showNonJavaResources`
   */
  javaProjectExplorerShowNonJavaResources: "java.project.explorer.showNonJavaResources",
  /**
   * %contributes.commands.java.project.explorer.hideNonJavaResources%
   * @value `java.project.explorer.hideNonJavaResources`
   */
  javaProjectExplorerHideNonJavaResources: "java.project.explorer.hideNonJavaResources",
  /**
   * %contributes.commands.java.view.package.revealFileInOS%
   * @value `java.view.package.revealFileInOS`
   */
  javaViewPackageRevealFileInOS: "java.view.package.revealFileInOS",
  /**
   * %contributes.commands.java.view.package.exportJar%
   * @value `java.view.package.exportJar`
   */
  javaViewPackageExportJar: "java.view.package.exportJar",
  /**
   * %contributes.commands.java.view.package.copyFilePath%
   * @value `java.view.package.copyFilePath`
   */
  javaViewPackageCopyFilePath: "java.view.package.copyFilePath",
  /**
   * %contributes.commands.java.view.package.copyRelativeFilePath%
   * @value `java.view.package.copyRelativeFilePath`
   */
  javaViewPackageCopyRelativeFilePath: "java.view.package.copyRelativeFilePath",
  /**
   * %contributes.commands.java.view.package.new%
   * @value `java.view.package.new`
   */
  javaViewPackageNew: "java.view.package.new",
  /**
   * %contributes.commands.java.view.menus.file.newJavaClass%
   * @value `java.view.menus.file.newJavaClass`
   */
  javaViewMenusFileNewJavaClass: "java.view.menus.file.newJavaClass",
  /**
   * %contributes.commands.java.view.package.newJavaClass%
   * @value `java.view.package.newJavaClass`
   */
  javaViewPackageNewJavaClass: "java.view.package.newJavaClass",
  /**
   * %contributes.commands.java.view.package.newJavaInterface%
   * @value `java.view.package.newJavaInterface`
   */
  javaViewPackageNewJavaInterface: "java.view.package.newJavaInterface",
  /**
   * %contributes.commands.java.view.package.newJavaEnum%
   * @value `java.view.package.newJavaEnum`
   */
  javaViewPackageNewJavaEnum: "java.view.package.newJavaEnum",
  /**
   * %contributes.commands.java.view.package.newJavaRecord%
   * @value `java.view.package.newJavaRecord`
   */
  javaViewPackageNewJavaRecord: "java.view.package.newJavaRecord",
  /**
   * %contributes.commands.java.view.package.newJavaAnnotation%
   * @value `java.view.package.newJavaAnnotation`
   */
  javaViewPackageNewJavaAnnotation: "java.view.package.newJavaAnnotation",
  /**
   * %contributes.commands.java.view.package.newJavaAbstractClass%
   * @value `java.view.package.newJavaAbstractClass`
   */
  javaViewPackageNewJavaAbstractClass: "java.view.package.newJavaAbstractClass",
  /**
   * %contributes.commands.java.view.package.newPackage%
   * @value `java.view.package.newPackage`
   */
  javaViewPackageNewPackage: "java.view.package.newPackage",
  /**
   * %contributes.commands.java.view.fileExplorer.newPackage%
   * @value `java.view.fileExplorer.newPackage`
   */
  javaViewFileExplorerNewPackage: "java.view.fileExplorer.newPackage",
  /**
   * %contributes.commands.java.view.package.newFile%
   * @value `java.view.package.newFile`
   */
  javaViewPackageNewFile: "java.view.package.newFile",
  /**
   * %contributes.commands.java.view.package.newFolder%
   * @value `java.view.package.newFolder`
   */
  javaViewPackageNewFolder: "java.view.package.newFolder",
  /**
   * %contributes.commands.java.view.package.moveFileToTrash%
   * @value `java.view.package.moveFileToTrash`
   */
  javaViewPackageMoveFileToTrash: "java.view.package.moveFileToTrash",
  /**
   * %contributes.commands.java.view.package.deleteFilePermanently%
   * @value `java.view.package.deleteFilePermanently`
   */
  javaViewPackageDeleteFilePermanently: "java.view.package.deleteFilePermanently",
  /**
   * %contributes.commands.java.view.package.renameFile%
   * @value `java.view.package.renameFile`
   */
  javaViewPackageRenameFile: "java.view.package.renameFile",
  /**
   * %contributes.commands.java.view.modernizeJavaProject%
   * @value `_java.view.modernizeJavaProject`
   */
  javaViewModernizeJavaProject: "_java.view.modernizeJavaProject",
  /**
   * %contributes.commands.java.upgradeWithCopilot%
   * @value `_java.upgradeWithCopilot`
   */
  javaUpgradeWithCopilot: "_java.upgradeWithCopilot",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "java.dependency.showMembers"
  | "java.dependency.syncWithFolderExplorer"
  | "java.dependency.autoRefresh"
  | "java.dependency.refreshDelay"
  | "java.dependency.packagePresentation"
  | "java.dependency.enableDependencyCheckup"
  | "java.project.exportJar.targetPath"
  | "java.project.explorer.showNonJavaResources"

export interface ConfigKeyTypeMap {
  "java.dependency.showMembers": boolean,
  "java.dependency.syncWithFolderExplorer": boolean,
  "java.dependency.autoRefresh": boolean,
  "java.dependency.refreshDelay": number,
  "java.dependency.packagePresentation": ("flat" | "hierarchical"),
  "java.dependency.enableDependencyCheckup": boolean,
  "java.project.exportJar.targetPath": string,
  "java.project.explorer.showNonJavaResources": boolean,
}

export interface ConfigShorthandMap {
  javaDependencyShowMembers: "java.dependency.showMembers",
  javaDependencySyncWithFolderExplorer: "java.dependency.syncWithFolderExplorer",
  javaDependencyAutoRefresh: "java.dependency.autoRefresh",
  javaDependencyRefreshDelay: "java.dependency.refreshDelay",
  javaDependencyPackagePresentation: "java.dependency.packagePresentation",
  javaDependencyEnableDependencyCheckup: "java.dependency.enableDependencyCheckup",
  javaProjectExportJarTargetPath: "java.project.exportJar.targetPath",
  javaProjectExplorerShowNonJavaResources: "java.project.explorer.showNonJavaResources",
}

export interface ConfigShorthandTypeMap {
  javaDependencyShowMembers: boolean,
  javaDependencySyncWithFolderExplorer: boolean,
  javaDependencyAutoRefresh: boolean,
  javaDependencyRefreshDelay: number,
  javaDependencyPackagePresentation: ("flat" | "hierarchical"),
  javaDependencyEnableDependencyCheckup: boolean,
  javaProjectExportJarTargetPath: string,
  javaProjectExplorerShowNonJavaResources: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `vscjava.vscode-java-dependency`
 */
export const configs = {
  /**
   * %configuration.java.dependency.showMembers%
   * @key `java.dependency.showMembers`
   * @default `false`
   * @type `boolean`
   */
  javaDependencyShowMembers: {
    key: "java.dependency.showMembers",
    default: false,
  } as ConfigItem<"java.dependency.showMembers">,
  /**
   * %configuration.java.dependency.syncWithFolderExplorer%
   * @key `java.dependency.syncWithFolderExplorer`
   * @default `true`
   * @type `boolean`
   */
  javaDependencySyncWithFolderExplorer: {
    key: "java.dependency.syncWithFolderExplorer",
    default: true,
  } as ConfigItem<"java.dependency.syncWithFolderExplorer">,
  /**
   * %configuration.java.dependency.autoRefresh%
   * @key `java.dependency.autoRefresh`
   * @default `true`
   * @type `boolean`
   */
  javaDependencyAutoRefresh: {
    key: "java.dependency.autoRefresh",
    default: true,
  } as ConfigItem<"java.dependency.autoRefresh">,
  /**
   * %configuration.java.dependency.refreshDelay%
   * @key `java.dependency.refreshDelay`
   * @default `2000`
   * @type `number`
   */
  javaDependencyRefreshDelay: {
    key: "java.dependency.refreshDelay",
    default: 2000,
  } as ConfigItem<"java.dependency.refreshDelay">,
  /**
   * %configuration.java.dependency.packagePresentation%
   * @key `java.dependency.packagePresentation`
   * @default `"flat"`
   * @type `string`
   */
  javaDependencyPackagePresentation: {
    key: "java.dependency.packagePresentation",
    default: "flat",
  } as ConfigItem<"java.dependency.packagePresentation">,
  /**
   * %configuration.java.dependency.enableDependencyCheckup%
   * @key `java.dependency.enableDependencyCheckup`
   * @default `true`
   * @type `boolean`
   */
  javaDependencyEnableDependencyCheckup: {
    key: "java.dependency.enableDependencyCheckup",
    default: true,
  } as ConfigItem<"java.dependency.enableDependencyCheckup">,
  /**
   *
   * @key `java.project.exportJar.targetPath`
   * @default `"${workspaceFolder}/${workspaceFolderBasename}.jar"`
   * @type `string`
   */
  javaProjectExportJarTargetPath: {
    key: "java.project.exportJar.targetPath",
    default: "${workspaceFolder}/${workspaceFolderBasename}.jar",
  } as ConfigItem<"java.project.exportJar.targetPath">,
  /**
   * %configuration.java.project.explorer.showNonJavaResources%
   * @key `java.project.explorer.showNonJavaResources`
   * @default `true`
   * @type `boolean`
   */
  javaProjectExplorerShowNonJavaResources: {
    key: "java.project.explorer.showNonJavaResources",
    default: true,
  } as ConfigItem<"java.project.explorer.showNonJavaResources">,
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "vscode-java-dependency",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "java": {
    "dependency": {
      "showMembers": boolean,
      "syncWithFolderExplorer": boolean,
      "autoRefresh": boolean,
      "refreshDelay": number,
      "packagePresentation": ("flat" | "hierarchical"),
      "enableDependencyCheckup": boolean,
    },
    "project": {
      "exportJar": {
        "targetPath": string,
      },
      "explorer": {
        "showNonJavaResources": boolean,
      },
    },
  },
}

export interface NestedScopedConfigs {
}


/**
 * Type union of all task definitions
 */
export type TaskType =
  | "java (buildArtifact)"
  | "java (build)"
  | "java"

export interface TaskPropertiesMap {
  "java (buildArtifact)": {
    "label": (string | undefined),
    "mainClass": (string | undefined),
    "targetPath": (string | undefined),
    "elements": (unknown[] | undefined),
  },
  "java (build)": {
    "paths": unknown[],
    "isFullBuild": boolean,
  },
  "java": {
    "label": (string | undefined),
    "mainClass": (string | undefined),
    "targetPath": (string | undefined),
    "elements": (unknown[] | undefined),
  },
}
